tap "git-friendly/git-friendly"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "python@3.8"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "circleci"
brew "coreutils"
brew "direnv"
brew "entr"
brew "findutils"
brew "fish"
brew "fzf"
brew "git"
brew "glances"
brew "grep"
brew "jq"
brew "mas"
brew "node"
brew "shellcheck"
brew "shfmt"
brew "terminal-notifier"
brew "thefuck"
brew "tree"
brew "wifi-password"
brew "yarn"
brew "git-friendly/git-friendly/git-friendly"
brew "github/gh/gh"
cask "1password"
cask "1password-cli"
cask "airflow"
cask "appcleaner"
cask "cyberghost-vpn"
cask "datagrip"
cask "discord"
cask "docker"
cask "easyfind"
cask "firefox-developer-edition"
cask "font-hack"
cask "franz"
cask "google-chrome"
cask "grandperspective"
cask "hyperswitch"
cask "iterm2"
cask "kap"
cask "keka"
cask "logitech-options"
cask "postman"
cask "raindropio"
cask "rectangle"
cask "slack"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
