tap "bearer/tap"
tap "bwhaley/ssmsh", "https://github.com/bwhaley/ssmsh"
tap "github/gh"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jesseduffield/lazygit"
brew "aws-sam-cli"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "coreutils"
brew "deno"
brew "direnv"
brew "dust"
brew "duti"
brew "entr"
brew "fd"
brew "harfbuzz"
brew "ffmpeg"
brew "findutils"
brew "fish"
brew "fisher"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"
brew "go"
brew "netpbm"
brew "graphviz"
brew "grep"
brew "hub"
brew "jq"
brew "ktfmt"
brew "libpq", link: true
brew "mas"
brew "ncdu"
brew "nmap"
brew "openjdk@21"
brew "pkgconf"
brew "python@3.9"
brew "ripgrep"
brew "rustup"
brew "shellcheck"
brew "shfmt"
brew "symlinks"
brew "terminal-notifier"
brew "tree"
brew "wget"
brew "wifi-password"
brew "yq"
brew "yt-dlp"
brew "bearer/tap/bearer"
brew "bwhaley/ssmsh/ssmsh"
brew "hashicorp/tap/terraform"
brew "jesseduffield/lazygit/lazygit"
cask "1password"
cask "1password-cli"
cask "airflow"
cask "appcleaner"
cask "arc"
cask "brave-browser"
cask "cursor"
cask "discord"
cask "docker"
cask "easyfind"
cask "figma"
cask "firefox@developer-edition"
cask "font-hack"
cask "gitbutler"
cask "gitify"
cask "google-chrome"
cask "google-cloud-sdk"
cask "grandperspective"
cask "handbrake"
cask "iina"
cask "insomnia"
cask "intellij-idea"
cask "iterm2"
cask "jordanbaird-ice"
cask "kap"
cask "keka"
cask "mac-mouse-fix"
cask "notion"
cask "postman"
cask "raycast"
cask "reaper"
cask "rectangle"
cask "reflex"
cask "shottr"
cask "slack"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "todoist"
cask "transmission"
cask "tuple"
cask "visual-studio-code"
cask "vlc"
mas "ColorSlurp", id: 1287239339
mas "Dato", id: 1470584107
mas "Dropover", id: 1355679052
mas "DuckDuckGo Privacy for Safari", id: 1482920575
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "‎WhatsApp", id: 310633997
